### ISSUE TITLE
Discard history before a certain point?

### ISSUE THREAD

**Issue by joshcho** [mmabrouk/chatgpt-wrapper#321]
**Is your feature request related to a problem? Please describe.**
I sometimes find that history gets long (and API costs more expensive), but I only need to maintain a tail of the history to continue the conversation. It would be neat if we can discard any history before a chat message.

**Describe the solution you'd like**
/discard-before {message-number} 

You stop considering any messages before {message-number} when sending the request to API. 

**Describe alternatives you've considered**
I haven't found a good solution for this, other than restarting the conversation.

**Comment by thehunmonkgroup** [comment]
`/help max-submission-tokens`

**Comment by joshcho** [comment]
I am aware of max-submission-tokens (should have mentioned in alternatives). Going back in history would dynamically solve the problem, as you can control how far back you want to send to the program.

This is something that vanilla ChatGPT can't do, and would be nice if added to chatgpt-wrapper.

**Comment by thehunmonkgroup** [comment]
I'm not seeing the use case.

The entire purpose of conversation tracking is to give the AI context for responding. If that context isn't needed, then start a new conversation.

It's also trivial to ask the AI to write a summary of the last portion of a conversation which can be used to bootstrap a new conversation.

And if cost is the concern, then `max-submission-tokens` is the right tool.

**Comment by joshcho** [comment]
How do you set max-submission-tokens? Here is my config for preset:

```
metadata:
  name: gpt-4
  provider: chat_openai
model_customizations:
  max_submission_tokens: 10
  model_name: gpt-4
  n: 1
  request_timeout: null
  streaming: true
  temperature: 1.0
```

Doesn't quite work.

>> Invalid key max_submission_tokens.
